version: "3.3"
services:
  homepage:
    image: ghcr.io/benphelps/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - /path/to/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
    environment: # (optional) For securely passing environment variable values as secrets
      - HOMEPAGE_VAR_UDM_PRO=${HOMEPAGE_VAR_UDM_PRO}
      - HOMEPAGE_VAR_PI_HOLE=${HOMEPAGE_VAR_PI_HOLE}
      - HOMEPAGE_VAR_NGINX_PM=${HOMEPAGE_VAR_NGINX_PM}
      - HOMEPAGE_VAR_CLOUDFLARE_ACCOUNTID=${HOMEPAGE_VAR_CLOUDFLARE_ACCOUNTID}
      - HOMEPAGE_VAR_CLOUDFLARE_TUNNELID=${HOMEPAGE_VAR_CLOUDFLARE_TUNNELID}
      - HOMEPAGE_VAR_CLOUDFLARE_KEY=${HOMEPAGE_VAR_CLOUDFLARE_KEY}
      - HOMEPAGE_VAR_PLEX=${HOMEPAGE_VAR_PLEX}
      - HOMEPAGE_VAR_TAUTULLI=${HOMEPAGE_VAR_TAUTULLI}
      - HOMEPAGE_VAR_AUDIOBOOKSHELF=${HOMEPAGE_VAR_AUDIOBOOKSHELF}
      - HOMEPAGE_VAR_OVERSEERR=${HOMEPAGE_VAR_OVERSEERR}
      - HOMEPAGE_VAR_RADARR=${HOMEPAGE_VAR_RADARR}
      - HOMEPAGE_VAR_SONARR=${HOMEPAGE_VAR_SONARR}
      - HOMEPAGE_VAR_READARR=${HOMEPAGE_VAR_READARR}
      - HOMEPAGE_VAR_PROWLARR=${HOMEPAGE_VAR_PROWLARR}
      - HOMEPAGE_VAR_BAZARR=${HOMEPAGE_VAR_BAZARR}
      - HOMEPAGE_VAR_QBIT=${HOMEPAGE_VAR_QBIT}
      - HOMEPAGE_VAR_PORTAINER=${HOMEPAGE_VAR_PORTAINER}
      - HOMEPAGE_VAR_WATCHTOWER=${HOMEPAGE_VAR_WATCHTOWER}
      - HOMEPAGE_VAR_PXMX_USER=${HOMEPAGE_VAR_PXMX_USER}
      - HOMEPAGE_VAR_PXMX_PW=${HOMEPAGE_VAR_PXMX_PW}
      - HOMEPAGE_VAR_TRUENAS=${HOMEPAGE_VAR_TRUENAS}
      - HOMEPAGE_VAR_NEXTCLOUD=${HOMEPAGE_VAR_NEXTCLOUD}
    restart: unless-stopped
